# RGB/WS2812 underglow (RGB LEDs are always powered, no ext_power control)
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# EC11 编码器
CONFIG_SENSOR=y
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
